name: logo_plot
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - Click
  - pytest
  - coverage
  - flake8
  - seaborn
  - pyqt5>=5.15.4
  - PyQt5-zip
  - openpyxl
  - pip
  - pip:
    - logomaker
    - PyQt5